project_id = "exaerohroycbdvhjqrqe"

[functions.analyze-diagram]
verify_jwt = false

[functions.generate-diagram]
verify_jwt = false

[functions.share-diagram]
verify_jwt = false

[functions.diagram-crypto]
verify_jwt = false
